# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Exsell' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Exsell
	pod 'Firebase'
	pod 'Firebase/Core'
	pod 'Firebase/Firestore'
 
  target 'ExsellTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExsellUITests' do
    # Pods for testing
  end

end
